baseURL = "https://distr1.org/"
languageCode = "en-us"
title = "distri"
theme = "distri"
disableKinds = ["RSS", "taxonomyTerm"]
publishDir = "../docs/"
enableRobotsTXT = true

[markup.goldmark.renderer]
# Required for e.g. <img> tags in markdown articles.
unsafe = true

[menu]

  [[menu.main]]
    name = "blog"
    title = "Blog"
    url = "https://michael.stapelberg.ch/posts/tags/distri/"
    weight = 40

  [[menu.main]]
    name = "github"
    title = "GitHub"
    url = "https://github.com/distr1/distri"
    weight = 60
